ctrl_interface=/var/run/wpa_supplicant
update_config=1
country=CR

# Red principal - conexión automática
network={
    ssid="Casa Miguel 2.4G"
    psk="Res20est22"
    key_mgmt=WPA-PSK
    priority=10
}
