# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-embeddedcar"
BBFILE_PATTERN_meta-embeddedcar = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-embeddedcar = "10"

LAYERDEPENDS_meta-embeddedcar = "core raspberrypi"
LAYERSERIES_COMPAT_meta-embeddedcar = "scarthgap"
